stages:
  train:
    cmd: python src/models/train_model.py
    deps:
      - data/processed
      - src/models/train_model.py
    outs:
      - models:
          persist: true
    metrics:
      - reports/validation_report.json:
          cache: false
  reports:
    cmd: python src/models/generate_reports.py
    deps:
      - data/processed
      - models
      - src/models/generate_reports.py
  process_data:
    cmd: python src/data/make_dataset.py
    deps:
      - data/raw
      - src/data/make_dataset.py
    outs:
      - data/processed:
          persist: true
