# main.yaml
paths:
  raw: 
    submission: data/raw/submission.xslx
    train: data/raw/xslx.xslx
  processed: 
    test: data/processed/test.parquet
    train: data/processed/train.parquet
    submission: data/processed/submission.parquet

make_dataset:
  split_size: 0.2
  random_state: 42
  target: is_churn
  features:
  - user_lifetime_visit_share
  - user_engagement
  - user_visit_frequency
  - user_days_since_first_billing
  - gym_days_since_first_visit
  - gym_category
  - gym_visit_frequency
  - user_age
  - years_usage
  - user_age_group
  - gym_last_60_days_visits
  - gyms_5km
  - user_last_60_days_visits
  - user_days_since_first_visit
  - months_usage
  - user_plan
  - user_lifetime_visits
  - user_days_since_first_gym_visit
  - user_last_60_days_visit_share
